# Site settings
title: john nadeau
email: me@johnnadeau.me
description: > # this means to ignore newlines until "baseurl:"
  I'm a developer at QueueDr.
  I mostly blog about my adventures coding,
  but like to talk about my life off the keyboard too.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnnadeau.me" # the base hostname & protocol for your site
twitter_username: johnnadeau
github_username:  johnnadeau

# Build settings
markdown: kramdown

# Permalinks
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 5
